# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Fri Oct 27 13:01:33 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 662)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.currentSlide = QtGui.QGroupBox(self.frame)
        self.currentSlide.setObjectName("currentSlide")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.currentSlide)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.slideSelector = QtGui.QComboBox(self.currentSlide)
        self.slideSelector.setObjectName("slideSelector")
        self.verticalLayout_7.addWidget(self.slideSelector)
        self.verticalLayout_5.addWidget(self.currentSlide)
        self.castersBox = QtGui.QGroupBox(self.frame)
        self.castersBox.setObjectName("castersBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.castersBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.casterName2 = QtGui.QLineEdit(self.castersBox)
        self.casterName2.setObjectName("casterName2")
        self.verticalLayout.addWidget(self.casterName2)
        self.casterName1 = QtGui.QLineEdit(self.castersBox)
        self.casterName1.setObjectName("casterName1")
        self.verticalLayout.addWidget(self.casterName1)
        self.castersShort = QtGui.QLineEdit(self.castersBox)
        self.castersShort.setObjectName("castersShort")
        self.verticalLayout.addWidget(self.castersShort)
        self.verticalLayout_5.addWidget(self.castersBox)
        self.twitterBox = QtGui.QGroupBox(self.frame)
        self.twitterBox.setObjectName("twitterBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.twitterBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.twitterHandles = QtGui.QLineEdit(self.twitterBox)
        self.twitterHandles.setObjectName("twitterHandles")
        self.verticalLayout_2.addWidget(self.twitterHandles)
        self.verticalLayout_5.addWidget(self.twitterBox)
        self.gamesBox = QtGui.QGroupBox(self.frame)
        self.gamesBox.setObjectName("gamesBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gamesBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gameWinsTop = QtGui.QLineEdit(self.gamesBox)
        self.gameWinsTop.setObjectName("gameWinsTop")
        self.verticalLayout_6.addWidget(self.gameWinsTop)
        self.gameWinsBottom = QtGui.QLineEdit(self.gamesBox)
        self.gameWinsBottom.setObjectName("gameWinsBottom")
        self.verticalLayout_6.addWidget(self.gameWinsBottom)
        self.verticalLayout_5.addWidget(self.gamesBox)
        self.roundBox = QtGui.QGroupBox(self.frame)
        self.roundBox.setObjectName("roundBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.roundBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.roundInformation = QtGui.QLineEdit(self.roundBox)
        self.roundInformation.setObjectName("roundInformation")
        self.verticalLayout_3.addWidget(self.roundInformation)
        self.playerRecord1 = QtGui.QLineEdit(self.roundBox)
        self.playerRecord1.setObjectName("playerRecord1")
        self.verticalLayout_3.addWidget(self.playerRecord1)
        self.playerRecord2 = QtGui.QLineEdit(self.roundBox)
        self.playerRecord2.setObjectName("playerRecord2")
        self.verticalLayout_3.addWidget(self.playerRecord2)
        self.verticalLayout_5.addWidget(self.roundBox)
        self.eventBox = QtGui.QGroupBox(self.frame)
        self.eventBox.setObjectName("eventBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.eventBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hashTag = QtGui.QLineEdit(self.eventBox)
        self.hashTag.setObjectName("hashTag")
        self.verticalLayout_4.addWidget(self.hashTag)
        self.verticalLayout_5.addWidget(self.eventBox)
        self.horizontalLayout.addWidget(self.frame)
        self.buttonBox = QtGui.QGroupBox(self.centralwidget)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.buttonBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.startRound = QtGui.QPushButton(self.buttonBox)
        self.startRound.setObjectName("startRound")
        self.verticalLayout_8.addWidget(self.startRound)
        self.showBooth = QtGui.QPushButton(self.buttonBox)
        self.showBooth.setObjectName("showBooth")
        self.verticalLayout_8.addWidget(self.showBooth)
        self.showSlide = QtGui.QPushButton(self.buttonBox)
        self.showSlide.setObjectName("showSlide")
        self.verticalLayout_8.addWidget(self.showSlide)
        self.showGameScreen = QtGui.QPushButton(self.buttonBox)
        self.showGameScreen.setObjectName("showGameScreen")
        self.verticalLayout_8.addWidget(self.showGameScreen)
        self.endRound = QtGui.QPushButton(self.buttonBox)
        self.endRound.setObjectName("endRound")
        self.verticalLayout_8.addWidget(self.endRound)
        self.horizontalLayout.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 603, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Hex Coverage Dashboard", None, QtGui.QApplication.UnicodeUTF8))
        self.currentSlide.setTitle(QtGui.QApplication.translate("MainWindow", "Slide Selector", None, QtGui.QApplication.UnicodeUTF8))
        self.castersBox.setTitle(QtGui.QApplication.translate("MainWindow", "Caster Names", None, QtGui.QApplication.UnicodeUTF8))
        self.casterName2.setText(QtGui.QApplication.translate("MainWindow", "Caster One", None, QtGui.QApplication.UnicodeUTF8))
        self.casterName1.setText(QtGui.QApplication.translate("MainWindow", "Caster Two", None, QtGui.QApplication.UnicodeUTF8))
        self.castersShort.setText(QtGui.QApplication.translate("MainWindow", "One & Two", None, QtGui.QApplication.UnicodeUTF8))
        self.twitterBox.setTitle(QtGui.QApplication.translate("MainWindow", "Twitter Handles", None, QtGui.QApplication.UnicodeUTF8))
        self.twitterHandles.setText(QtGui.QApplication.translate("MainWindow", "@CastOne & @CastTwo", None, QtGui.QApplication.UnicodeUTF8))
        self.gamesBox.setTitle(QtGui.QApplication.translate("MainWindow", "Game Wins", None, QtGui.QApplication.UnicodeUTF8))
        self.gameWinsTop.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.gameWinsBottom.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.roundBox.setTitle(QtGui.QApplication.translate("MainWindow", "Round Information", None, QtGui.QApplication.UnicodeUTF8))
        self.roundInformation.setText(QtGui.QApplication.translate("MainWindow", "Round X of Y", None, QtGui.QApplication.UnicodeUTF8))
        self.playerRecord1.setText(QtGui.QApplication.translate("MainWindow", "A-B", None, QtGui.QApplication.UnicodeUTF8))
        self.playerRecord2.setText(QtGui.QApplication.translate("MainWindow", "C-D", None, QtGui.QApplication.UnicodeUTF8))
        self.eventBox.setTitle(QtGui.QApplication.translate("MainWindow", "Event Information", None, QtGui.QApplication.UnicodeUTF8))
        self.hashTag.setText(QtGui.QApplication.translate("MainWindow", "#HexEvent", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBox.setTitle(QtGui.QApplication.translate("MainWindow", "Scene Control", None, QtGui.QApplication.UnicodeUTF8))
        self.startRound.setText(QtGui.QApplication.translate("MainWindow", "Start Round", None, QtGui.QApplication.UnicodeUTF8))
        self.showBooth.setText(QtGui.QApplication.translate("MainWindow", "Show Booth", None, QtGui.QApplication.UnicodeUTF8))
        self.showSlide.setText(QtGui.QApplication.translate("MainWindow", "Show Current Slide", None, QtGui.QApplication.UnicodeUTF8))
        self.showGameScreen.setText(QtGui.QApplication.translate("MainWindow", "Show Game Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.endRound.setText(QtGui.QApplication.translate("MainWindow", "End Round", None, QtGui.QApplication.UnicodeUTF8))

